### ISSUE TITLE
对令牌过期的描述与Mojang的Yggdrasil实现不符

### ISSUE THREAD

**Issue by yushijinhun** [to2mbn/authlib-injector#5]
对Mojang的Yggdrasil服务端发出以下请求，行为与文档描述的不一致：

<details>

```yaml
actions:
- type: authenticate
  request:
    username: ******
    password: ******
    clientToken: a4e0147b7d254d17a01050390abe0e6d # -> $c1
  response:
    accessToken: 6b70c76057744e579c4777d90c69b46b # -> $a1
    clientToken: a4e0147b7d254d17a01050390abe0e6d # $c1

- type: authenticate
  request:
    username: ******
    password: ******
  response:
    accessToken: be9bbcc2b31a45b3b94e1948f6f031ad # -> $a2
    clientToken: cf37f0dc4ed9499cb2ba182e5c456c0d # -> $c2

- type: validate
  request:
    accessToken: 6b70c76057744e579c4777d90c69b46b # $a1
  response:
    error: ForbiddenOperationException

- type: validate
  request:
    accessToken: be9bbcc2b31a45b3b94e1948f6f031ad # $a2
  response: {} # 204

- type: refresh
  request:
    accessToken: 6b70c76057744e579c4777d90c69b46b # $a1
  response:
    accessToken: 713586718473440a85f66d93f10e425a # -> $a3
    clientToken: a4e0147b7d254d17a01050390abe0e6d # $c1

- type: validate
  request:
    accessToken: 6b70c76057744e579c4777d90c69b46b # $a1
  response:
    error: ForbiddenOperationException

- type: validate
  request:
    accessToken: 713586718473440a85f66d93f10e425a # $a3
  response: {} # 204

- type: validate
  request:
    accessToken: be9bbcc2b31a45b3b94e1948f6f031ad # $a2
  response:
    error: ForbiddenOperationException

- type: refresh
  request:
    accessToken: be9bbcc2b31a45b3b94e1948f6f031ad # $a2
  response:
    accessToken: d9031657c43546d993fc306b9b4a18f3 # -> $a4
    clientToken: cf37f0dc4ed9499cb2ba182e5c456c0d # -> $c2

```

</details>
